networks:
  extern-net:
  aka-net:

volumes:
  pgdata:

x-app-environment: &app-environment
  DATABASE_URL: postgres://${POSTGRES_USER:-relayfunder}:${POSTGRES_PASSWORD:-relayfunder}@database:5432/${POSTGRES_DB:-relayfunder_dev}
  NODE_ENV: development
  CI: "true"

services:
  database:
    image: postgres:16.11
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-relayfunder}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-relayfunder}
      POSTGRES_DB: ${POSTGRES_DB:-relayfunder_dev}
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-relayfunder} -d ${POSTGRES_DB:-relayfunder_dev}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      aka-net:
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_PORT:-3001}:80"
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@local.host}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    profiles:
      - develop
    networks:
      aka-net:

  app:
    build:
      context: .
      target: devrunner
    depends_on:
      - database
    ports:
      - "${DEV_APP_PORT:-3000}:3000"
      - "${PRISMA_STUDIO_PORT:-5555}:5555"
    volumes:
      - ./:/app
      - ./lib/sentry-dev.ts:/app/lib/sentry.ts
      # - ./dev_modules/app/node_modules:/app/node_modules
      - ./dev_modules/app/.next:/app/.next
      - ./dev_modules/pnpm_store:/app/.pnpm-store
    environment:
      <<: *app-environment
    networks:
      extern-net:
      aka-net:

  app-shell:
    build:
      context: .
      target: devrunner
    command: /bin/bash
    depends_on:
      - app
    volumes_from:
      - app
    environment:
      <<: *app-environment
    profiles:
      - shell
    networks:
      aka-net:

  app-trace:
    build:
      context: .
      target: devrunner
    command: "pnpm next internal turbo-trace-server .next/trace-turbopack"
    # apk add socat ; socat -d -d TCP4-LISTEN:5747,bind=172.20.0.3,fork TCP4:localhost:5747 & ;
    ports:
      - 5747:5747
    volumes_from:
      - app
    environment:
      <<: *app-environment
    profiles:
      - debug
    networks:
      extern-net:
